name: Auto Version Bump and Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  bump_version_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Make Compressed Release
        run: |
          wget https://github.com/astral-sh/uv/releases/download/0.5.13/uv-x86_64-pc-windows-msvc.zip
          unzip uv-x86_64-pc-windows-msvc.zip
          rm uvx.exe
          echo "./uv.exe run ./main.py" >> start.bat
          rm -rf .git
          rm -rf .github
          rm -rf ci
          rm -rf tests
          zip -r ${{ github.workspace }}/gpt-a-l-v${{ steps.bump_version.outputs.new_version }}.zip .
        shell: bash

      - name: Publish Release
        uses: softprops/action-gh-release@v2.1.0
        with:
          tag_name: ${{ steps.bump_version.outputs.new_version }}
          files: ${{ github.workspace }}/gpt-a-l-v${{ steps.bump_version.outputs.new_version }}.zip
          draft: false
          fail_on_unmatched_files: true
          generate_release_notes: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}