name: Update Version
on:
  push:
    tags:
      - '*.*.*'

jobs:
  format-code:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python
        uses: actions/setup-python@v5.3.0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install semver

      - name: Bump version in JSON file
        id: bump_version
        run: |
          import json
          from semver import VersionInfo
          with open('version', 'r') as f:
              data = json.load(f)
              current_version = data.get("version", "0.0.0")
              new_version = str(VersionInfo.parse(current_version).bump_patch())
              data["version"] = new_version
          with open('version', 'w') as f:
              json.dump(data, f, indent=2)
          print(f"::set-output name=new_version::{new_version}")
        shell: python

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Bump version to ${{ steps.bump_version.outputs.new_version }}"
          branch: master
